apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kube-state-metrics
spec:
  ports:
  - name: http-metrics
    port: 8080 
    targetPort: http-metrics 
  selector:
    app.kubernetes.io/name: kube-state-metrics 
  type: ClusterIP 
