  apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: node-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-exporter
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: node-exporter
        image: quay.io/prometheus/node-exporter:v1.7.0
        args:
        - --path.rootfs=/hostroot
        ports:
        - name: metrics
          containerPort: 9100
        volumeMounts:
        - name: rootfs
          mountPath: /hostroot
          readOnly: true
      volumes:
      - name: rootfs
        hostPath:
          path: /
          type: Directory
